### ISSUE TITLE
Restrict breadscrumbs to only 2 levels

### ISSUE THREAD

**Issue by protagonist51** [mikelunn/angular2-breadcrumb#2]
How to restrict breadscrumbs to only 2 levels like Home/Customer and replacing it with Customer/Detail in next clicks?

**Comment by mikelunn** [comment]
@protagonist51 Thanks for your interest in this project, and sorry for such a late response. It defeats the purpose of the component to only restrict it to two levels. However, please feel free to fork and customize it to achieve whatever use-case you may be trying to solve.
